# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
#flag

name: Build and deploy ASP.Net Core app to Azure Web App - WebCalculator111

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  DOTNET_VERSION: '3.1.301'
  WEBAPP_PATH: 'src/WebCalc'
  CALC_PATH: 'src/Calculator'
jobs:
  build-web-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: |
          cd ${{ env.WEBAPP_PATH }}
          dotnet build --configuration Release

      - name: dotnet publish
        run: |
          cd ${{ env.WEBAPP_PATH }}
          dotnet publish -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ env.WEBAPP_PATH }}/myapp

  deploy-web-app:
    runs-on: ubuntu-latest
    needs: build-web-app
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'WebCalculator111'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E6C50C0A65804F0BA14524A20BFA7883 }}
          package: .

  deploy-calculators:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd ${{ env.CALC_PATH }}
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'FunctionCalculatotSubtract'
          slot-name: 'Production'
          package: '${{ env.CALC_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_48023FD56F6D4AD198D95061F77FBD03 }}

      - name: 'Publish Add Calculator'
        uses: Azure/functions-action@v1
        with:
          app-name: 'AddCalculator'
          slot-name: 'Production'
          package: '${{ env.CALC_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CDA710F4BB524EAC914DEDC66F732837 }}

  production-test-add-calculator:
    runs-on: ubuntu-latest
    needs: deploy-calculators
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
    
      - name: 'Run add function GET-tests'
        run: |
          cd src/CalculatorTest
          bash curltests.sh '${{ secrets.ADDITIONENDPOINT }}' add
  
  production-test-sub-calculator:
    runs-on: ubuntu-latest
    needs: deploy-calculators
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
    
      - name: 'Run add function GET-tests'
        run: |
          cd src/CalculatorTest
          bash curltests.sh '${{ secrets.SUBTRACTIONENDPOINT }}' sub